name: "Build"
defaults:
  run:
    shell: bash
env:
  DOCKER_REGISTRY: hazeldeploy
  DOCKER_IMAGE_NAME: ecs-deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: Check Out Repo
            uses: actions/checkout@v2

          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1

          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: ./Dockerfile
              push: true
              tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ENV.DOCKER_REGISTRY}}/${{ENV.DOCKER_IMAGE_NAME}}:latest .

          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}

#
#
#
#
#
#
#
#
#    steps:
#      - name: Checkout Code
#        uses: actions/checkout@v2
#
#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{ secrets.DOCKERHUB_USERNAME }}
#          password: ${{ secrets.DOCKERHUB_TOKEN }}
#
#      - name: Build Image
#        run: |
#          docker build -t $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest .
#
##      - name: Collect docker logs
##        uses: jwalton/gh-docker-logs@v1
##        with:
##          dest: './logs'
##
##      - name: Tar logs
##        run: tar cvzf ./logs.tgz ./logs
##
##      - name: Upload logs to GitHub
##        uses: actions/upload-artifact@master
##        with:
##          name: logs.tgz
##          path: ./logs.tgz
#
#      - name: Push
#        run: |
#          docker push $DOCKER_REGISTRY/$DOCKER_IMAGE_NAME:latest
#
#       - name: Image digest
#              run: echo ${{ steps.docker_build.outputs.digest }}
