name: "Build"
defaults:
  run:
    shell: bash
env:
  DOCKER_REGISTRY: hazeldeploy
  DOCKER_IMAGE_NAME: ecs-deploy

on:
  push:
    branches:
      - master
      - develop
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
          - name: Check Out Repo
            uses: actions/checkout@v2

          - name: Login to Docker Hub
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1

          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              context: ./
              file: ./Dockerfile
              push: true
              tags: hazeldeploy/ecs-deploy:latest

          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }} > digest.txt

          - uses: actions/upload-artifact@v1
            with:
              name: digest
              path: ./digest.txt

          - name: Get Time
            id: time
            uses: nanzm/get-time-action@v1.1
            with:
              timeZone: 8
              format: 'YYYY-MM-DD-HH-mm'

          - uses: marvinpinto/action-automatic-releases@latest
            with:
              repo_token: "${{ secrets.GITHUB_TOKEN }}"
              automatic_release_tag: "latest"
              prerelease: false
              title: Release at ${{ steps.time.outputs.time }}
              files: digest.txt
